# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

pod 'Kingfisher'

target 'Kingfisher' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kingfisher

end

target 'YCImageScoller' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YCImageScoller

end

target 'YCImageScollerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YCImageScollerDemo

end
